### ISSUE TITLE
Beginner Question: How to add configuration to use it behind an Load-Balancer

### ISSUE THREAD

**Issue by christianbenz** [thomasdarimont/embedded-spring-boot-keycloak-server#23]
Hi,

I´m trying to run the keycloak server on AWS - ElasticBeanstalk (ELB) in a VPC with a Load-Balancer and NAT-Gateway in front.
So SSL-Cert is on the Domain, but not on the ELB-Instance with the keycloak-server.

When I try to login to the admin-console I have the problem, that the auth-server-url is a regular http-request and not a https.

I found a possible solution, but I don´t know where to do these configuration in the project:
" ... make sure that you have set "proxy-address-forwarding=true" in your standalone.xml configuration of Wildfly."

Thank you in advance for every help / advice,
Christian.

**Comment by thomasdarimont** [comment]
Hello @christianbenz 

I think you need to set:
```
server:
  forward-headers-strategy: native
```
in your application config file.
See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes#deprecations-in-spring-boot-22

I adjusted the examples via 7190e0762cb87d97d83ff66a0242ddac76c53d25
