### ISSUE TITLE
Remove Undertow dependency when using Jetty profile

### ISSUE THREAD

**Issue by nigredo-tori** [thomasdarimont/embedded-spring-boot-keycloak-server#27]
[Here](https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/blob/3a9cec2896687290a8db943ee9c7823b71de3da0/pom.xml#L57-L60) Undertow starter is specified as a dependency, meaning that it is a part of both profiles. Instead, we should specify it as a dependency for the `undertow` profile (this is already done), and possibly mark that profile as the default (so that we don't break the dependent projects).

**Comment by thomasdarimont** [comment]
Fixed via 41ad8ef
