### ISSUE TITLE
Update to Spring Boot 2.4.3

### ISSUE THREAD

**Issue by tubbynl** [thomasdarimont/embedded-spring-boot-keycloak-server#36]
https://spring.io/blog/2021/02/18/spring-boot-2-4-3-is-now-available

unfortunately it's a bit unpleasant that the maven parent is overridden so this becomes a lib problem, i'll try to provide a pull request if i find the time for it

**Comment by tubbynl** [comment]
this starter is nice work btw 👍

**Comment by thomasdarimont** [comment]
Fixed via b34ee690ad1bbcef53ac15b36de3d61bc7e78362

**Comment by tubbynl** [comment]
tnx :)
