### ISSUE TITLE
Maven not finding version 5

### ISSUE THREAD

**Issue by ebremer** [thomasdarimont/embedded-spring-boot-keycloak-server#55]
I tried rebuilding my project with 5.0.0 but it wasn't finding it.  All earlier versions work fine.  Is there time needed before it become available via Jitpack?

**Comment by topikachu** [comment]
https://jitpack.io/com/github/thomasdarimont/embedded-spring-boot-keycloak-server/5.0.0/build.log
The build failed at jitpack build.
@thomasdarimont Could you fix or release a new version?


Thanks

**Comment by ebremer** [comment]
https://jitpack.io/#thomasdarimont/embedded-spring-boot-keycloak-server

**Comment by thomasdarimont** [comment]
Sorry for the delay. It seems that the git environment on jitpack.io is broken and thus the build fails.
I just released 5.0.1 with an updated git-commit-id-plugin for a try to fix the issue.

**Comment by thomasdarimont** [comment]
It seems that the git-commit-id-plugin uses an unsupported parameter for the git log command.

Downgraded the git-commit-id-plugin to 4.0.4 with a try to workaround the issue, see 3339a755681b4ed54ff0a091cb355dab1f222a7b.

Just released 5.0.2 lets see if this works.

**Comment by thomasdarimont** [comment]
3339a75 works :)

The release 5.0.2 seems to work fine :)
