### ISSUE TITLE
With keycloak >=15.1.x and above resteasy.allowGzip must be "false"

### ISSUE THREAD

**Issue by jmax01** [thomasdarimont/embedded-spring-boot-keycloak-server#63]
https://github.com/thomasdarimont/embedded-spring-boot-keycloak-server/blob/ebeaa0b3f2352617da9c651921ba3770943e8b20/embedded-keycloak-server-spring-boot-support/src/main/java/com/github/thomasdarimont/keycloak/embedded/EmbeddedKeycloakConfig.java#L87

At least when using undertow.

**Comment by jmax01** [comment]
PR #64

**Comment by hydra1983** [comment]
I spent a whole day to get this fixed...

**Comment by hydra1983** [comment]
I spent a whole day to get this fixed...

**Comment by thomasdarimont** [comment]
This is fixed in 5.1.0/6.0.0/7.0.0
